services:
  djr-postgres:
    image: postgres:latest
    hostname: djr-postgres
    container_name: djr-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "djangoredis"
      POSTGRES_PASSWORD: "djangoredis!"
      POSTGRES_DB: djangoredis
    volumes:
      - ../postgres/data/:/var/lib/postgresql
    networks:
      - django-redis-project

  djr-redis:
    image: redis:alpine
    hostname: djr-redis
    container_name: djr-redis
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379
    volumes:
      - ../redis/data:/data
      - ../redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server --port 6379
    networks:
      - django-redis-project


networks:
  django-redis-project:
    driver: bridge